### ISSUE TITLE
Pytorch_lightning exception when running example.json

### ISSUE THREAD

**Issue by SophieSchau** [utcsilab/deepinpy#11]
**Issue**:

When running the `readme` example I am seeing the following error:
```
(deepinpy) bash-3.2$ python main.py --config configs/example.json
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main_train(args)
  File "main.py", line 46, in main_train
    trainer = Trainer(max_epochs=args.num_epochs, gpus=1, logger=tt_logger, default_save_path='./logs', early_stop_callback=None, distributed_backend=None, accumulate_grad_batches=args.num_accumulate)
  File "/Users/schauman/miniconda3/envs/deepinpy/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 578, in __init__
    self.data_parallel_device_ids = parse_gpu_ids(gpus)
  File "/Users/schauman/miniconda3/envs/deepinpy/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 563, in parse_gpu_ids
    gpus = sanitize_gpu_ids(gpus)
  File "/Users/schauman/miniconda3/envs/deepinpy/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 533, in sanitize_gpu_ids
    raise MisconfigurationException(message)
pytorch_lightning.utilities.debugging.MisconfigurationException: 
            You requested GPUs: [0]
            But your machine only has: []
```

I tried to follow the build instructions in the `readme` but came across a few issues, such as a conflict between `pillow` and `pytorch_lightning` [0], `num_workers` needing to be > 0, and a missing but required key/value in the `example.json` file (`distributed_training`). 

I was hoping to contribute to the project so I'm happy to submit a PR with my fixes if you'd like! 

[0] https://github.com/facebookresearch/detectron2/issues/612

**Comment by SophieSchau** [comment]
Hey! I just checked out `2ec586ebe53cc6aa83cbb68354647f35c9c1ad12` which is the unit tests changes you made 6 days ago and it worked, so it looks like something has broken since then.

**Comment by jtamir** [comment]
Thanks for testing this out! Are you testing with CPU or GPU?

If CPU, then you should add ‘“cpu”: true’ to the config, and yes num_workers should reflect the number of cpus. 

In general we need to get the unit tests back up to speed to test all the different cases so that when I add a value it doesn’t break!
I will check tomorrow, thanks!

**Comment by SophieSchau** [comment]
Thanks! Yes, I was trying to test it on a CPU. It works when I add `"cpu": true`. I will keep playing around with it, and I am happy to work on getting the unit tests up to speed too!

**Comment by jtamir** [comment]
Hi @SophieSchau is this still an issue?
I have pushed fixes to the unit tests and tested with pytorch lightning 0.7.1

**Comment by SophieSchau** [comment]
Sorry for not getting back to you sooner. The installation seems to work now! Thanks.
