### ISSUE TITLE
bug in cgsense.py

### ISSUE THREAD

**Issue by nmickevicius** [utcsilab/deepinpy#12]
I am attempting to run a CGSenseRecon on my own data just to get familiar with the library before trying some DL reconstructions. In cgsense.py, there looks to be a bug in the forward() function in the call to ConjGrad(). Instead of eps=self.hparams.eps, should it be eps=self.hparams.cg_eps? 

As an aside, do you have any guidelines on how to view the output of a CGSenseRecon? Is there an h5 file output somewhere that I might be missing?

**Comment by jtamir** [comment]
Thanks, this was a bug from my code refactor changes recently.
If you run Tensorboard, you can see the output as shown in the README. Currently I do not save the training results to h5. If you would like to contribute this feature, it would be much appreciated! Future work will add validation and test, and then it makes sense to save to h5.
